# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('industry', models.CharField(blank=True, max_length=500)),
                ('company_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='uploads/users/')),
                ('position', models.CharField(blank=True, max_length=400)),
                ('work_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('work_address', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='uploads/company/logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
